sudo: required

dist: trusty

language: cpp

compiler:
  - clang
  - gcc

install:
  - wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha9/premake-5.0.0-alpha9-linux.tar.gz -O /tmp/premake5.tar.gz
  - tar -xvf /tmp/premake5.tar.gz
  - sudo ldconfig
  - ./premake5 gmake

script: make all
